# Generated by Django 4.2.2 on 2023-06-16 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=90, validators=[django.core.validators.RegexValidator(message='Invalid name.', regex='^[A-Za-záéíóúñÁÉÍÓÚÑ\\s]+$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=90, validators=[django.core.validators.RegexValidator(message='Invalid surname.', regex='^[A-Za-záéíóúñÁÉÍÓÚÑ\\s]+$')], verbose_name='surname'),
        ),
    ]
